# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

use_frameworks!
target 'WhiteBoard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'SnapKit', '~> 3.0.2'
  pod 'Alamofire', '~> 4.0'
  pod 'Socket.IO-Client-Swift', '~> 8.2.0'


  # Pods for WhiteBoard

#  target 'WhiteBoardTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

#  target 'WhiteBoardUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
